sudo: false
cache: bundler
language: ruby
env:
  matrix:
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=postgres
    - SOLIDUS_BRANCH=v1.4 DB=mysql
    - SOLIDUS_BRANCH=v1.4 DB=postgres
    - SOLIDUS_BRANCH=v2.0 DB=mysql
    - SOLIDUS_BRANCH=v2.0 DB=postgres
script:
  - bundle exec rake test_app
  - bundle exec rspec
rvm:
  - 2.3.3
