module ShortShipReturnInvoiceSoapResponses
  def short_ship_return_invoice_gettax_response(doc_code: 'asdf')
    {
      transaction_id: "4533642402940720",
      result_code: "Success",
      doc_id: "85696863",
      doc_type: "ReturnInvoice",
      doc_code: doc_code,
      doc_date: "2015-05-15",
      doc_status: "Committed",
      reconciled: false,
      timestamp: "2015-05-15T13:30:40+00:00",
      total_amount: "0",
      total_discount: "0",
      total_exemption: "0",
      total_taxable: "0",
      total_tax: "0",
      total_tax_calculated: "0",
      hash_code: "0",
      tax_lines: {
        tax_line: {
          no: "3478149",
          tax_code: "PC040144",
          taxability: true,
          boundary_level: "Address",
          exemption: "0",
          discount: "0",
          taxable: "0",
          rate: "0.066000",
          tax: "0",
          tax_calculated: "0",
          tax_included: false,
          tax_details: {
            tax_detail: [
              {
                country: "US",
                region: "UT",
                juris_type: "State",
                juris_code: "49",
                tax_type: "Sales",
                base: "0",
                taxable: "0",
                rate: "0.047000",
                tax: "0",
                tax_calculated: "0",
                non_taxable: "0",
                exemption: "0",
                juris_name: "UTAH",
                tax_name: "UT STATE TAX",
                tax_authority_type: "45",
                tax_group: nil,
                rate_type: "G",
                state_assigned_no: nil,
              },
              {
                country: "US",
                region: "UT",
                juris_type: "County",
                juris_code: "005",
                tax_type: "Sales",
                base: "0",
                taxable: "0",
                rate: "0.001000",
                tax: "0",
                tax_calculated: "0",
                non_taxable: "0",
                exemption: "0",
                juris_name: "CACHE",
                tax_name: "UT COUNTY TAX",
                tax_authority_type: "45",
                tax_group: nil,
                rate_type: "G",
                state_assigned_no: "03-038"},
              {
                country: "US",
                region: "UT",
                juris_type: "City",
                juris_code: "45860",
                tax_type: "Sales",
                base: "0",
                taxable: "0",
                rate: "0.010000",
                tax: "0",
                tax_calculated: "0",
                non_taxable: "0",
                exemption: "0",
                juris_name: "LOGAN",
                tax_name: "UT CITY TAX",
                tax_authority_type: "45",
                tax_group: nil,
                rate_type: "G",
                state_assigned_no: "03-038",
               },
              {
                country: "US",
                region: "UT",
                juris_type: "Special",
                juris_code: "BTNM",
                tax_type: "Sales",
                base: "0",
                taxable: "0",
                rate: "0.002500",
                tax: "0",
                tax_calculated: "0",
                non_taxable: "0",
                exemption: "0",
                juris_name: "CACHE CO TR",
                tax_name: "UT SPECIAL TAX",
                tax_authority_type: "45",
                tax_group: nil,
                rate_type: "G",
                state_assigned_no: "03-038"},
              {
                country: "US",
                region: "UT",
                juris_type: "Special",
                juris_code: "DTTR",
                tax_type: "Sales",
                base: "0",
                taxable: "0",
                rate: "0.005500",
                tax: "0",
                tax_calculated: "0",
                non_taxable: "0",
                exemption: "0",
                juris_name: "LOGAN TR SP",
                tax_name: "UT SPECIAL TAX",
                tax_authority_type: "45",
                tax_group: nil,
                rate_type: "G",
                state_assigned_no: "03-038",
              }
            ]
          },
          exempt_cert_id: "0",
          tax_date: "2015-05-14",
          reporting_date: "2015-05-15",
          accounting_method: "Accrual",
        },
      },
      tax_addresses: {
        tax_address: {
          address: "1362 N 1720 E",
          address_code: "1",
          boundary_level: "0",
          city: "Logan",
          country: "US",
          postal_code: "84341",
          region: "UT",
          tax_region_id: "2106677",
          juris_code: "4900545860",
          latitude: nil,
          longitude: nil,
          geocode_type: "StreetLevel",
          validate_status: "NormalHit",
          distance_to_boundary: "0",
        },
      },
      locked: false,
      adjustment_reason: "0",
      adjustment_description: nil,
      version: "1",
      tax_date: "2015-05-15",
      tax_summary: nil,
      volatile_tax_rates: false,
      messages: [
        {
          summary: nil,
          details: nil,
          helplink: nil,
          refersto: nil,
          severity: nil,
          source: nil,
        },
      ],
    }
  end
end
